-- CreateTable
CREATE TABLE `Usuario` (
    `IDUSUARIO` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME_USUARIO` VARCHAR(30) NOT NULL,
    `SENHA` VARCHAR(255) NOT NULL,
    `FUNCAO` VARCHAR(30) NOT NULL,

    UNIQUE INDEX `Usuario_NOME_USUARIO_key`(`NOME_USUARIO`),
    PRIMARY KEY (`IDUSUARIO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `todo` (
    `IDTODO` INTEGER NOT NULL AUTO_INCREMENT,
    `TITLE` VARCHAR(20) NOT NULL,
    `DESCRIPTION` VARCHAR(255) NOT NULL,

    PRIMARY KEY (`IDTODO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
