site_name: Extra Gestão
site_author: José
site_description: Site voltado para a documentação do Grupo Extra Gestão em Requisitos de Software
repo_url: https://github.com/mdsreq-fga-unb/2025.1-T02-ExtraGestao
repo_name: 2025.1-T02-ExtraGestao

nav:
  - Sobre: index.md
  - "Unidade 1":
      - "Cenário Atual do Cliente e do Negócio": vpp/cenario-atual-do-cliente-e-do-negocio.md
      - "Solução Proposta" : vpp/solucao-proposta.md
      - "Estratégias de Engenharia de Software" : vpp/estrategias-de-engenharia-de-software.md
      - "Cronograma de Entregas": vpp/crono-programa-de-entregas.md
      - "Interação Entre Equipe e Cliente": vpp/interacao-entre-equipe-e-cliente.md

  - "Unidade 2":
      - "Requisitos": vpp/requisitos/requisitos.md
      - "Backlog do Produto": vpp/backlog-do-produto.md

  - "Processo ER":
      - "Processo de Engenharia de Requisitos": er/processo-de-engenharia-de-requisitos.md

  - "Apresentações":
      - "Apresentação 1": vpp/apresentacao.md

  - "Estudos de caso":
      - "PBB": estudos-de-caso/pbb.md
      - "USM": estudos-de-caso/usm.md
      - "DIAGRAMA": estudos-de-caso/casosdeuso.md
  
  - "Caso de uso":
      - "Caso de Uso: Criar perfil do paciente": casos-de-uso/caso-de-uso-1.md

  - "Pautas":
      - "Pauta 1": pautas/pauta1.md
      - "Pauta 2": pautas/pauta2.md
      - "Pauta 3": pautas/pauta3.md
      - "Pauta 4": pautas/pauta4.md
      - "Pauta 5": pautas/pauta5.md
      - "Pauta 6": pautas/pauta6.md
      - "Pauta 7": pautas/pauta7.md
      - "Pauta 8": pautas/pauta8.md
      - "Pauta 9": pautas/pauta9.md
      - "Pauta 10": pautas/pauta10.md

  - "Protótipo":
      - "Protótipo de Alta Fidelidade": prototipos/prototipoAlta.md

  - "Produto":
  


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer

  disable_nav_previous_next: true

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Trocar para modo escuro

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Trocar para modo claro

  favicon: assets/favicon.ico
  logo: assets/favicon.ico

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_css: [stylesheets/extra.css]